# Generated by Django 3.0.8 on 2020-07-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('celular', models.CharField(max_length=9)),
            ],
        ),
    ]
