# Generated by Django 3.0.8 on 2020-07-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=60, verbose_name='Razon Social')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=35)),
            ],
        ),
    ]
