# Generated by Django 3.0.8 on 2020-08-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20200722_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabecera_venta',
            name='ruc',
        ),
    ]
